/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_etfbl_prs_prs112212_z4_Hash */

#ifndef _Included_net_etfbl_prs_prs112212_z4_Hash
#define _Included_net_etfbl_prs_prs112212_z4_Hash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_etfbl_prs_prs112212_z4_Hash
 * Method:    getHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_etfbl_prs_prs112212_1z4_Hash_getHash(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
